config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :order_details, only: [:update]

    resources :orders, only: %i[show update]

    resources :customers, only: %i[index show edit update]

    resources :genres, only: %i[index create edit update]

    resources :items, only: %i[new show index edit create update]

    root to: 'homes#top'
  end

  scope module: 'public' do
    resources :addresses, only: %i[index edit create update destroy]

    resources :orders, only: %i[new index show create] do
      collection do
        post :confirm
        get :thanks
      end
    end

    resources :cart_items, only: %i[create update index destroy] do
      collection do
        delete :destroy_all
      end
    end

    controller :customers do
      get 'customers/my_page', action: :show
      get 'customers/information/edit', action: :edit
      patch 'customers/information', action: :update
      get 'customers/unsubscribe', action: :unsubscribe
      patch 'customers/withdraw', action: :withdraw
    end

    resources :items, only: %i[show index]

    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
  end

  # 顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # 管理者用
  devise_for :admin, skip: %i[registrations passwords], controllers: {
    sessions: 'admin/sessions'
  }
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { pending: 0, confirmation: 1, production: 2, preparation: 3, shipment: 4 }
  after_initialize :set_defaults

  def set_defaults
    self.shipping_cost ||= 800
  end

  belongs_to :customer
  has_many :order_details, dependent: :destroy
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params_for_status_update)
      if @order.confirmation?
        @order.order_details.each do |order_detail|
          order_detail.update(making_status: 'pending')
        end
      end
      flash[:notice] = '注文ステータスを更新しました'
      redirect_to admin_order_path(@order)
    else
      @order_details = @order.order_details
      flash[:alert] = '注文ステータスの更新に失敗しました'
      render :show
    end
  end

  def order_params_for_status_update
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container mt-4">
  <div class="row mb-4">
    <div class="col-md-4">
      <h3 class="bg-light rounded px-3 py-2 d-inline-block">注文履歴詳細</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <h5>注文情報</h5>
      <div class="row mb-2">
        <div class="col-sm-3 fw-bold">購入者</div>
        <div class="col-sm-9"><%= link_to @order.customer.last_name + @order.customer.first_name, admin_customer_path(@order.customer) %></div>
      </div>
      <div class="row mb-2">
        <div class="col-sm-3 fw-bold">注文日</div>
        <div class="col-sm-9"><%= @order.created_at.strftime('%Y/%m/%d') %></div>
      </div>
      <div class="row mb-2">
        <div class="col-sm-3 fw-bold">配送先</div>
        <div class="col-sm-9">
          〒<%= @order.postal_code %><br>
          <%= @order.address %><br>
          <%= @order.name %>
        </div>
      </div>
      <div class="row mb-4">
        <div class="col-sm-3 fw-bold">支払方法</div>
        <div class="col-sm-9"><%= @order.payment_method_i18n %></div>
      </div>
      <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true, class: "row gx-3 align-items-center mb-4" do |f| %>
        <div class="col-sm-3">
          <%= f.label :status, "注文ステータス", class: "col-form-label fw-bold" %>
        </div>
        <div class="col-auto">
          <%= f.select :status, Order.statuses.keys.map { |k| [Order.statuses_i18n[k], k] }, {}, { class: "form-select form-select-sm" } %>
        </div>
        <div class="col-auto">
          <%= f.submit "更新", class: "btn btn-success btn-sm" %>
        </div>
      <% end %>
      <h5 class="mt-4">注文内容</h5>
      <table class="table table-bordered align-middle">
        <thead style="background-color: #f0f0f0;">
          <tr>
            <th>商品名</th>
            <th class="text-end">単価(税込)</th>
            <th class="text-end">数量</th>
            <th class="text-end">小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |detail| %>
            <tr>
              <td><%= detail.item.name %></td>
              <td class="text-end"><%= number_to_currency(detail.price, unit: "円", precision: 0) %></td>
              <td class="text-end"><%= detail.amount %></td>
              <td class="text-end"><%= number_to_currency(detail.price * detail.amount, unit: "円", precision: 0) %></td>
              <td>
                <%= form_with model: detail, url: admin_order_detail_path(detail), method: :patch, local: true, class: "d-flex align-items-center mb-0" do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |k| [OrderDetail.making_statuses_i18n[k], k] }, {}, { class: "form-select form-select-sm" } %>
                  <%= f.submit "更新", class: "btn btn-success btn-sm mx-2" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-4">
      <h5>請求情報</h5>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th scope="row" class="table-light" style="width: 40%;">商品合計</th>
            <td class="text-end"><%= number_to_currency(@order.order_details.sum { |detail| detail.price * detail.amount }, unit: "円", precision: 0) %></td>
          </tr>
          <tr>
            <th scope="row" class="table-light">送料</th>
            <td class="text-end"><%= number_to_currency(@order.shipping_cost, unit: "円", precision: 0) %></td>
          </tr>
          <tr>
            <th scope="row" class="table-light">請求金額合計</th>
            <td class="text-end fw-bold"><%= number_to_currency(@order.total_payment, unit: "円", precision: 0) %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>