config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :order_details, only: [:update]

    resources :orders, only: %i[show update]

    resources :customers, only: %i[index show edit update]

    resources :genres, only: %i[index create edit update]

    resources :items, only: %i[new show index edit create update]

    root to: 'homes#top'
  end

  scope module: 'public' do
    resources :addresses, only: %i[index edit create update destroy]

    resources :orders, only: %i[new index show create] do
      collection do
        post :confirm
        get :thanks
      end
    end

    resources :cart_items, only: %i[create update index destroy] do
      collection do
        delete :destroy_all
      end
    end

    controller :customers do
      get 'customers/my_page', action: :show
      get 'customers/information/edit', action: :edit
      patch 'customers/information', action: :update
      get 'customers/unsubscribe', action: :unsubscribe
      patch 'customers/withdraw', action: :withdraw
    end

    resources :items, only: %i[show index]

    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
  end

  # 顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }

  # 管理者用
  devise_for :admin, skip: %i[registrations passwords], controllers: {
    sessions: 'admin/sessions'
  }
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  validates :amount, presence: true

  def subtotal
    item.tax_included_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def active_for_authentication?
    super && (is_active == true)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: { in: [true, false] }

  def tax_included_price
    (price * 1.1).floor
  end

  has_one_attached :item_image

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { pending: 0, confirmation: 1, production: 2, preparation: 3, shipment: 4 }
  after_initialize :set_defaults

  def set_defaults
    self.shipping_cost ||= 800
  end

  belongs_to :customer
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { unavailable: 0, pending: 1, production: 2, completed: 3 }

  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      flash.now[:alert] = 'ジャンル名を入力してください'
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      flash.now[:alert] = 'ジャンル名を入力してください'
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.order(created_at: :desc).page(params[:page]) # includesで一括読み込み
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = if params[:search].present?
               Item.where('name LIKE ?', "%#{params[:search]}%").order(created_at: :desc).page(params[:page]).per(10)
             else
               Item.order(created_at: :desc).page(params[:page]).per(10)
             end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: '商品が登録されました'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: '商品情報が更新されました'
    else
      flash.now[:alert] = '商品情報の更新に失敗しました'
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :item_image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_namespace?
    request.fullpath.start_with?('/admin')
  end
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header_nav.erb
  <% if admin_signed_in? %>
  <li class="nav-item">
    <%= link_to '商品一覧', admin_items_path, class: 'nav-link text-dark' %>
  </li>
  <li class="nav-item">
    <%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-dark' %>
  </li>
  <li class="nav-item">
    <%= link_to '注文履歴一覧', admin_root_path, class: 'nav-link text-dark' %>
  </li>
  <li class="nav-item">
    <%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-dark' %>
  </li>
  <li class="nav-item">
    <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "ログイン", new_admin_session_path, class: 'nav-link text-dark' %>
  </li>
<% end %>

app/views/layouts/_public_header_nav.erb
  <% if customer_signed_in? %>
  <li class="nav-item">
    <%= link_to "マイページ", customers_my_page_path, class: 'nav-link text-dark' %>
  </li>
  <li class="nav-item">
    <%= link_to '商品一覧', items_path, class: 'nav-link text-dark' %>
  </li>
  <li class="nav-item">
    <%= link_to 'カート', cart_items_path, class: 'nav-link text-dark' %>
  </li>
  <li class="nav-item">
    <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "About", about_path, class: 'nav-link text-dark' %>
  </li>
  <li class="nav-item">
    <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
  </li>
  <li class="nav-item">
    <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
  </li>
  <li class="nav-item">
    <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/a95fdb4b13.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <%= link_to 'LOGO', root_path, class: 'border border-dark p-3 fw-bold fs-1 text-dark text-center' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_namespace? %>
                <%= render 'layouts/admin_header_nav' %>
                <div class="mt-1">
                  <% if admin_namespace? %>
                    <%= form_with url: admin_items_path, method: :get, local: true do |f| %>
                      <%= f.text_field :search, placeholder: "Search", value: params[:search] %>
                      <%= f.submit "🔍"%>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% else %>
              <%= render 'layouts/public_header_nav' %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main class='mb-auto'>
    <div class="mx-auto">
      <% flash.each do |message_type, message| %>
        <% css_class = case message_type.to_s
                 when 'notice'
                   'alert-success'
                 when 'success'
                   'alert-success'
                 when 'alert'
                   'alert-danger'
                 when 'danger'
                   'alert-danger'
                 when 'warning'
                   'alert-warning'
                 else
                   'alert-info'
                 end %>
        <div class="alert <%= css_class %> alert-dismissible fade show m-3" role="alert">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </main>
  <footer class="border-top py-3">
    <div class="container mt-3">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>